### ISSUE TITLE
trigger missing?

### ISSUE THREAD

**Issue by neutralinsomniac** [kris-nova/boopkit#1]
The README (and `remote/remote`) makes reference to the `trigger` binary, but it doesn't seem that there's source nor a Makefile rule to build it. Was this intentional?

**Comment by kris-nova** [comment]
There is a Makefile in the `/remote` directory. Just run `make remote` from [here](https://github.com/kris-nova/boopkit/blob/main/Makefile#L15-L17)

I need to update the code to also compile the trigger when just `make` is typed.

For now you can just use `make remote` which will `cd remote` and then run `make`.
